# Generated by Django 4.1.4 on 2023-01-01 09:48

from django.db import migrations
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users_app.models.CustomUserManager()),
            ],
        ),
    ]
