# Generated by Django 4.1.4 on 2023-01-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(default=False, verbose_name="Is Verified"),
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="is_email_verified",
            new_name="is_verified",
        ),
    ]
