# Generated by Django 4.1.4 on 2023-01-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users_app", "0003_remove_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_password_change",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Last Password Change"
            ),
        ),
    ]
